//
//  ShowDiscoveryViewController.swift
//  Explore
//
//  Created by Christian Graver on 03/01/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit
import Kingfisher

class PresentCastViewController: UIViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var imageView: UIImageView!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var regionLabel: UILabel!
    @IBOutlet weak var descriptionView: UITextView!
    
    // MARK: - Properties
    var cast: ShowCast.DisplayData.Cast!

    // MARK: - Init
    class func instantiate(cast: ShowCast.DisplayData.Cast) -> PresentCastViewController {
        let name = "\(PresentCastViewController.self)"
        let storyboard = UIStoryboard(name: name, bundle: nil)
        let vc = storyboard.instantiateViewController(withIdentifier: name) as! PresentCastViewController
        vc.cast = cast
        return vc
    }
    
    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    // MARK: - Actions
    @IBAction func playSoundPressed(_ sender: Any) {
    }
    
    // MARK: - Misc
    private func setupView() {
        if let imageString = cast.image,
            let filePath = Bundle.main.path(forResource: imageString, ofType: "jpg"),
            let image = UIImage(contentsOfFile: filePath) {
            imageView.image = image
        }
        
        nameLabel.text = cast.name
        regionLabel.text = cast.region
        
        if let description = cast.description {
            descriptionView.text = description
        }
    }
}
