//
//  MakeCastRouter.swift
//  Explore
//
//  Created by Christian Graver on 25/12/2018.
//  Copyright (c) 2018 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

@objc protocol MakeCastRoutingLogic {
}

protocol MakeCastDataPassing {
    var dataStore: MakeCastDataStore? { get }
}

class MakeCastRouter: NSObject, MakeCastDataPassing {
    weak var viewController: MakeCastViewController?
    var dataStore: MakeCastDataStore?
}

extension MakeCastRouter: MakeCastRoutingLogic {
    
}
