//
//  MakeCastInteractor.swift
//  Explore
//
//  Created by Christian Graver on 25/12/2018.
//  Copyright (c) 2018 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

protocol MakeCastBusinessLogic {
    func fetchStravaRoute(with id: String)
}

protocol MakeCastDataStore {
    //var name: String { get set }
}

class MakeCastInteractor: MakeCastDataStore {
    var presenter: MakeCastPresentationLogic?
    var worker = MakeCastWorker(stravaService: StravaServerRepository())
}

extension MakeCastInteractor: MakeCastBusinessLogic {
    func fetchStravaRoute(with id: String) {
        worker.fetchRoute(with: id) { (route) in
            if let route = route {
                self.presenter?.present(stravaRoute: route)
            } else {
                self.presenter?.presentError(messange: "Route not downloadable")
            }
        }
    }
}
