//
//  MakeCastModels.swift
//  Explore
//
//  Created by Christian Graver on 25/12/2018.
//  Copyright (c) 2018 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

enum MakeCast {
    enum Request { }
    enum Response { }
    enum DisplayData { }
}

extension MakeCast.Request {
    
}

extension MakeCast.Response {
    
}

extension MakeCast.DisplayData {
    
}
