//
//  MakeCastWorker.swift
//  Explore
//
//  Created by Christian Graver on 25/12/2018.
//  Copyright (c) 2018 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

class MakeCastWorker {
    let stravaService: StravaService
    
    init(stravaService: StravaService) {
        self.stravaService = stravaService
    }
    
    func fetchRoute(with id: String) {
        stravaService.getRoute(for: id) { response in
            switch response.result {
            case .success(let gxpString):
                print("This is the gxp string: \(gxpString)")
                let parser = MyParser(xml: gxpString)
                if let route = parser.parseXML()  {
                    print("Route has \(route.route.count) coordinates")
                }
                
            case .failure(_):
                print("Strava route failed!")
            }
        }
    }
}
