//
//  MakeCastViewController.swift
//  Explore
//
//  Created by Christian Graver on 25/12/2018.
//  Copyright (c) 2018 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

protocol MakeCastDisplayLogic: class {
}

class MakeCastViewController: UIViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var stravaRouteIdTextField: UITextField! {
        didSet {
            stravaRouteIdTextField.text = "16534173"
        }
    }
    
    // MARK: - Properties
    var interactor: MakeCastBusinessLogic?
    var router: (NSObjectProtocol & MakeCastRoutingLogic & MakeCastDataPassing)?
    
    // MARK: - Init
    class func instantiate() -> MakeCastViewController {
        let name = "\(MakeCastViewController.self)"
        let storyboard = UIStoryboard(name: name, bundle: nil)
        let vc = storyboard.instantiateViewController(withIdentifier: name) as! MakeCastViewController
        vc.setup()
        return vc
    }
    
    // MARK: - Setup
    private func setup() {
        let viewController = self
        let interactor = MakeCastInteractor()
        let presenter = MakeCastPresenter()
        let router = MakeCastRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: - Actions
    @IBAction func goPressed(_ sender: Any) {
        if let idString = stravaRouteIdTextField.text, !idString.isEmpty {
            interactor?.fetchStravaRoute(with: idString)
        }
    }
    
    // MARK: - Misc
}

// MARK: - MakeCastDisplayLogic
extension MakeCastViewController: MakeCastDisplayLogic {
    
}
