//
//  ExploreRouter.swift
//  Explore
//
//  Created by Christian Graver on 16/12/2018.
//  Copyright (c) 2018 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

@objc protocol ExploreRoutingLogic {
}

protocol ExploreDataPassing {
    var dataStore: ExploreDataStore? { get }
}

class ExploreRouter: NSObject, ExploreDataPassing {
    weak var viewController: ExploreViewController?
    var dataStore: ExploreDataStore?
}

extension ExploreRouter: ExploreRoutingLogic {
    
}
