//
//  ExploreModels.swift
//  Explore
//
//  Created by Christian Graver on 16/12/2018.
//  Copyright (c) 2018 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

enum Explore {
    enum Request { }
    enum Response { }
    enum DisplayData { }
}

extension Explore.Request {
    struct ViewCreated {}
    struct ExploreStart {}
    struct ExplorePause {}
    struct ExploreEnd {}
    struct DebugDiscoveryHit {}
}

extension Explore.Response {
    
}

extension Explore.DisplayData {
    struct Adventure {
        var name: String
        var points: [Explore.DisplayData.Disovery]
    }
    
    struct MapPoint {
        var lat: Double
        var long: Double
    }
    
    struct Disovery {
        var name: String
        var point:(Double, Double)
    }
    
    struct Distance {
        var distanceString: String
    }
}
