//
//  PickAreaPresenter.swift
//  Explore
//
//  Created by Christian Graver on 19/03/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

protocol PickAreaPresentationLogic {
    
}

class PickAreaPresenter {
    weak var viewController: PickAreaDisplayLogic?
}

extension PickAreaPresenter: PickAreaPresentationLogic {
    
}
