//
//  PickAreaInteractor.swift
//  Explore
//
//  Created by Christian Graver on 19/03/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

protocol PickAreaBusinessLogic {
}

protocol PickAreaDataStore {
    //var name: String { get set }
}

class PickAreaInteractor: PickAreaDataStore {
    var presenter: PickAreaPresentationLogic?
    var worker: PickAreaWorker?
}

extension PickAreaInteractor: PickAreaBusinessLogic {
    
}
