//
//  PickAreaViewController.swift
//  Explore
//
//  Created by Christian Graver on 19/03/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit
import Lottie
import SnapKit

protocol PickAreaDisplayLogic: class {
}

class PickAreaViewController: UIViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var contentView: UIView!
    @IBOutlet weak var worldOutlineImageView: UIImageView!
    @IBOutlet weak var nsButton: LottieButton!
    
    // MARK: - Properties
    var interactor: PickAreaBusinessLogic?
    var router: (NSObjectProtocol & PickAreaRoutingLogic & PickAreaDataPassing)?
    var nsPulseAnimation = AnimationView(name: "pulse-effect")
    
    // MARK: - Init
    class func instantiate() -> PickAreaViewController {
        let name = "\(PickAreaViewController.self)"
        let storyboard = UIStoryboard(name: name, bundle: nil)
        let vc = storyboard.instantiateViewController(withIdentifier: name) as! PickAreaViewController
        vc.setup()
        return vc
    }
    
    // MARK: - Setup
    private func setup() {
        let viewController = self
        let interactor = PickAreaInteractor()
        let presenter = PickAreaPresenter()
        let router = PickAreaRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    // MARK: - Actions
    @IBAction func knPressed(_ sender: Any) {
        print("knPressed")
    }
    
    // MARK: - Misc
    private func setupView() {
        // Setup scroll view
        scrollView.minimumZoomScale = 1.0
        scrollView.maximumZoomScale = 2.0
        scrollView.delegate = self
        
        view.backgroundColor = UIColor.gcDarkGreen
        
        worldOutlineImageView.image = worldOutlineImageView.image?.withRenderingMode(.alwaysTemplate)
        worldOutlineImageView.tintColor = .gcTextBrown
        
//        nsButton.imageView?.image = nsButton?.imageView?.image?.withRenderingMode(.alwaysTemplate)
//        nsButton.imageView?.tintColor = .white

//        nsButton.animationName = "pulse-effect"
//        nsButton.playAnimation()
        
        contentView.addSubview(nsPulseAnimation)
        contentView.sendSubviewToBack(nsPulseAnimation)
        nsPulseAnimation.snp.makeConstraints { (make) in
            make.center.equalTo(nsButton.snp.center)
            make.height.equalTo(nsButton.snp.height)
            make.width.equalTo(nsButton.snp.width)
        }
        nsPulseAnimation.loopMode = .loop
        nsPulseAnimation.play()
        nsPulseAnimation.alpha = 0.8
    }
}

// MARK: - PickAreaDisplayLogic
extension PickAreaViewController: PickAreaDisplayLogic {
    
}

extension PickAreaViewController: UIScrollViewDelegate {
    func viewForZooming(in scrollView: UIScrollView) -> UIView? {
        return contentView
    }
}
