//
//  PickAreaRouter.swift
//  Explore
//
//  Created by Christian Graver on 19/03/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

@objc protocol PickAreaRoutingLogic {
}

protocol PickAreaDataPassing {
    var dataStore: PickAreaDataStore? { get }
}

class PickAreaRouter: NSObject, PickAreaDataPassing {
    weak var viewController: PickAreaViewController?
    var dataStore: PickAreaDataStore?
}

extension PickAreaRouter: PickAreaRoutingLogic {
    
}
