//
//  IntroInteractor.swift
//  Explore
//
//  Created by Christian Graver on 26/02/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

protocol IntroBusinessLogic {
}

protocol IntroDataStore {
    //var name: String { get set }
}

class IntroInteractor: IntroDataStore {
    var presenter: IntroPresentationLogic?
    var worker: IntroWorker?
}

extension IntroInteractor: IntroBusinessLogic {
    
}
