//
//  IntroViewController.swift
//  Explore
//
//  Created by Christian Graver on 26/02/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

protocol IntroDisplayLogic: class {
}

class IntroViewController: UIViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var startButton: UIButton! {
        didSet {
            startButton.layer.borderWidth = 1
            startButton.layer.borderColor = UIColor.white.cgColor
            startButton.titleLabel?.text = "START"
            startButton.addText(spacing: 2.0)
        }
    }
    
    // MARK: - Properties
    var interactor: IntroBusinessLogic?
    var router: (NSObjectProtocol & IntroRoutingLogic & IntroDataPassing)?
    
    // MARK: - Init
    class func instantiate() -> IntroViewController {
        let name = "\(IntroViewController.self)"
        let storyboard = UIStoryboard(name: name, bundle: nil)
        let vc = storyboard.instantiateViewController(withIdentifier: name) as! IntroViewController
        vc.setup()
        return vc
    }
    
    // MARK: - Setup
    private func setup() {
        let viewController = self
        let interactor = IntroInteractor()
        let presenter = IntroPresenter()
        let router = IntroRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    // MARK: - Actions
    
    // MARK: - Misc
    private func setupView() {
        view.backgroundColor = .black
    }
}

// MARK: - IntroDisplayLogic
extension IntroViewController: IntroDisplayLogic {
    
}
