//
//  IntroModels.swift
//  Explore
//
//  Created by Christian Graver on 26/02/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

enum Intro {
    enum Request { }
    enum Response { }
    enum DisplayData { }
}

extension Intro.Request {
    
}

extension Intro.Response {
    
}

extension Intro.DisplayData {
    
}
