//
//  IntroPresenter.swift
//  Explore
//
//  Created by Christian Graver on 26/02/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

protocol IntroPresentationLogic {
    
}

class IntroPresenter {
    weak var viewController: IntroDisplayLogic?
}

extension IntroPresenter: IntroPresentationLogic {
    
}
