//
//  IntroRouter.swift
//  Explore
//
//  Created by Christian Graver on 26/02/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

@objc protocol IntroRoutingLogic {
}

protocol IntroDataPassing {
    var dataStore: IntroDataStore? { get }
}

class IntroRouter: NSObject, IntroDataPassing {
    weak var viewController: IntroViewController?
    var dataStore: IntroDataStore?
}

extension IntroRouter: IntroRoutingLogic {
    
}
