//
//  ListCastsInteractor.swift
//  Explore
//
//  Created by Christian Graver on 20/12/2018.
//  Copyright (c) 2018 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

protocol ListCastsBusinessLogic {
    func viewCreated(request: ListCasts.Request.ViewCreated)
    func didSelectCast(request: ListCasts.Request.CastSelected)
}

protocol ListCastsDataStore {
    var casts: [Cast] { get set }
}

class ListCastsInteractor: ListCastsDataStore {
    var presenter: ListCastsPresentationLogic?
    var worker = ListCastsWorker(service: MockRepository())
    
     var casts = [Cast]()
}

extension ListCastsInteractor: ListCastsBusinessLogic {
    func viewCreated(request: ListCasts.Request.ViewCreated) {
        worker.fetchCasts { (casts) in
            self.casts = casts
            self.presenter?.present(casts: casts)
        }
    }
    
    func didSelectCast(request: ListCasts.Request.CastSelected) {
        
    }
}
