//
//  ListCastsWorker.swift
//  Explore
//
//  Created by Christian Graver on 20/12/2018.
//  Copyright (c) 2018 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

class ListCastsWorker {
    let service: CastService
    init(service: CastService) {
        self.service = service
    }
    
    func fetchCasts(completion: @escaping ([Cast]) -> Void) {
        service.getCasts { (casts) in
            completion(casts)
        }
    }
}
