//
//  ListCastsPresenter.swift
//  Explore
//
//  Created by Christian Graver on 20/12/2018.
//  Copyright (c) 2018 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

protocol ListCastsPresentationLogic {
    func present(casts: [Cast])
}

class ListCastsPresenter {
    weak var viewController: ListCastsDisplayLogic?
}

extension ListCastsPresenter: ListCastsPresentationLogic {
    func present(casts: [Cast]) {
        let vms = casts.map { (cast) -> ListCasts.DisplayData.Cast in
            return ListCasts.DisplayData.Cast(name: cast.name, region: cast.region, numberOfDiscoveryPoints: cast.discoveryPoints.count)
        }
        viewController?.display(casts: vms)
    }
}
