//
//  ShowDiscoveryViewController.swift
//  Explore
//
//  Created by Christian Graver on 03/01/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit
import Kingfisher

protocol ShowDiscoveryDisplayLogic: class {
   // func setup(with discovery:ShowCast.DisplayData.Discovery)
}

class ShowDiscoveryViewController: UIViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var imageView: UIImageView!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var descriptionView: UITextView!
    @IBOutlet weak var playSoundButton: UIButton!
    
    // MARK: - Properties
    var discovery: ShowCast.DisplayData.Discovery!

    // MARK: - Init
    class func instantiate(discovery: ShowCast.DisplayData.Discovery) -> ShowDiscoveryViewController {
        let name = "\(ShowDiscoveryViewController.self)"
        let storyboard = UIStoryboard(name: name, bundle: nil)
        let vc = storyboard.instantiateViewController(withIdentifier: name) as! ShowDiscoveryViewController
        vc.discovery = discovery
        return vc
    }
    
    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    // MARK: - Actions
    @IBAction func playSoundPressed(_ sender: Any) {
    }
    
    // MARK: - Misc
    private func setupView() {
        if let imageString = discovery.image,
            let filePath = Bundle.main.path(forResource: imageString, ofType: "jpg"),
            let image = UIImage(contentsOfFile: filePath) {
            imageView.image = image
        }
        
        nameLabel.text = discovery.name
        
        if let description = discovery.description {
            descriptionView.text = description
        }
        
        playSoundButton.isHidden = !discovery.hasSound
    }
}

// MARK: - ShowDiscoveryDisplayLogic
extension ShowDiscoveryViewController: ShowDiscoveryDisplayLogic {
//    func setup(with discovery: ShowCast.DisplayData.Discovery) {
//        if let image = discovery.image {
//            imageView.kf.setImage(with: image)
//        }
//        if let description = discovery.description {
//            descriptionView.text = description
//        }
//        
//        playSoundButton.isHidden = !discovery.hasSound
//    }
}
