//
//  ShowCastInteractor.swift
//  Explore
//
//  Created by Christian Graver on 03/01/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

protocol ShowCastBusinessLogic {
    func viewCreated()
}

protocol ShowCastDataStore {
    var cast: Cast? { get set }
}

class ShowCastInteractor: ShowCastDataStore {
    var presenter: ShowCastPresentationLogic?
    var worker = ShowCastWorker(service: MockRepository())
    
    var cast: Cast?
}

extension ShowCastInteractor: ShowCastBusinessLogic {
    func viewCreated() {
        worker.getCast { (cast) in
            self.cast = cast
            self.presenter?.present(cast: cast)
        }
    }
}
