//
//  ShowCastPresenter.swift
//  Explore
//
//  Created by Christian Graver on 03/01/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

protocol ShowCastPresentationLogic {
    func present(cast: Cast)
}

class ShowCastPresenter {
    weak var viewController: ShowCastDisplayLogic?
}

extension ShowCastPresenter: ShowCastPresentationLogic {
    func present(cast: Cast) {
        
        let pointVMs = cast.discoveryPoints.map { (discovery) -> ShowCast.DisplayData.Discovery in
            return ShowCast.DisplayData.Discovery(name: discovery.name,
                                                  image: discovery.imageUrlString,
                                                  description: discovery.description,
                                                  hasSound: discovery.clip != nil,
                                                  point: (discovery.location.latitude, discovery.location.longitude))
        }
        
        let cast = ShowCast.DisplayData.Cast(name: cast.name, region: cast.region, image: cast.imageUrlString, description: cast.description, route: cast.stravaRoute!, points: pointVMs )
        viewController?.display(cast: cast)
    }
}
