//
//  ShowCastModels.swift
//  Explore
//
//  Created by Christian Graver on 03/01/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

enum ShowCast {
    enum Request { }
    enum Response { }
    enum DisplayData { }
}

extension ShowCast.Request {
    
}

extension ShowCast.Response {
    
}

extension ShowCast.DisplayData {
    struct Cast {
        var name: String
        var region: String
        var image: String?
        var description: String?
        var route: StravaRoute
        var points: [ShowCast.DisplayData.Discovery]
    }
    
    struct Discovery {
        var name: String
        var image: String?
        var description: String?
        var hasSound: Bool
        var point:(Double, Double)
    }
}
