//
//  ShowCastWorker.swift
//  Explore
//
//  Created by Christian Graver on 03/01/2019.
//  Copyright (c) 2019 nordgrus. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

class ShowCastWorker {
    let service: CastService
    
    init(service: CastService) {
        self.service = service
    }
    
    func getCast(completion: @escaping (Cast) -> Void) {
        service.getTestCast { (cast) in
            completion(cast)
        }
    }
}
